networks:
  micro:
    driver: bridge
    name: micro-test1

services:
  mysql:
    container_name: micro-mysql
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=user
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - TZ=Asia/Shanghai
    volumes:
      - ./config/sql:/docker-entrypoint-initdb.d/
      - micro-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - micro
#  redis:
#    container_name: redis
#    image: redis:latest
#    restart: always
#    ports:
#      - "6379:6379"
#    networks:
#      - micro-user
  user:
    container_name: micro-user
    image: wadesanity/micro-user:latest
    restart: always
    environment:
      - GIN_MODE=release
#    ports:
#      - "8081:8080"
    networks:
      - micro
  gateway:
    container_name: micro-gateway
    image: wadesanity/micro-gateway:latest
    restart: always
    environment:
      - GIN_MODE=release
    ports:
      - "8080:8080"
    networks:
      - micro

volumes:
  micro-mysql-data:
    name: micro-mysql-data