package main

import (
	"gateway/conf"
	"gateway/docs" // docs is generated by Swag CLI, you have to import it.
	"gateway/grpc/conn"
	"gateway/pkg/util"
	"gateway/router"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"     // gin-swagger middleware
	ginSwagger "github.com/swaggo/gin-swagger" // swagger embed files
)

//	@contact.name	API Support
//	@contact.url	http://www.swagger.io/support
//	@contact.email	support@swagger.io

// @license.name	Apache 2.0
// @license.url	http://www.apache.org/licenses/LICENSE-2.0.html
func main() {
	// programmatically set swagger info
	docs.SwaggerInfo.Title = "micro-case API"
	docs.SwaggerInfo.Description = "This is a easy gin-grpc server called micro-case."
	docs.SwaggerInfo.Version = "1.0"
	docs.SwaggerInfo.Host = "localhost:8080"
	docs.SwaggerInfo.BasePath = "/api/v1"
	docs.SwaggerInfo.Schemes = []string{"http", "https"}

	conf.Init()
	util.Init()
	connection := conn.Init()
	defer connection.Close()
	engine := gin.Default()
	engine.Use(gin.LoggerWithWriter(util.Logger.Out))
	router.InitRouter(engine)

	engine.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	err := engine.Run(":8080")
	if err != nil {
		util.Logger.Panicf("engine run err:%v", err)
		return
	}
}
